spring:
  mvc:
     static-path-pattern: /static/**
  datasource:
    url: jdbc:postgresql://localhost:32768/koupdatabase
    username: receiver
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate.ddl-auto: update
  thymeleaf:
    cache: false

captcha:
   google:
      recaptcha:
         secret-key: your-key
         public-key: your-key

email-sender:
   email: your-email
   password: your-email-password
   
logging:
  level:
    org.springframework.security: DEBUG
    